healthbot:
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50
    
    #joint controllers, joint names from the urdf `healthbot.xacro` file
    right_wheel_controller:
        type: effort_controllers/JointPositionController
        joint: healthbot__right_wheel_hinge
        pid: {p: 100.0, i: 0.01, d: 10.0}

    left_wheel_controller:
        type: effort_controllers/JointPositionController
        joint: healthbot__left_wheel_hinge
        pid: {p: 100.0, i: 0.01, d: 10.0}

    palm_riser_controller:
        type: effort_controllers/JointPositionController
        joint: healthbot__palm_riser
        pid: {p: 100.0, i: 0.01, d: 10.0}
        
    left_finger_controller:
        type: effort_controllers/JointPositionController
        joint: healthbot__left_finger
        pid: {p: 100.0, i: 0.01, d: 10.0}

    left_finger_tip_controller:
        type: effort_controllers/JointPositionController
        joint: healthbot__joint_left_finger_tip
        pid: {p: 100.0, i: 0.01, d: 10.0}

    right_finger_controller:
        type: effort_controllers/JointPositionController
        joint: healthbot__right_finger
        pid: {p: 100.0, i: 0.01, d: 10.0}
        
    right_finger_tip_controller:
        type: effort_controllers/JointPositionController
        joint: healthbot__joint_right_finger_tip
        pid: {p: 100.0, i: 0.01, d: 10.0}